name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.11
        with:
          heroku_api_key: ${{c1616628-be83-4292-b3aa-8e0d74c4e50e}}
          heroku_app_name: "peaceful-inlet-54998"
          heroku_email: "dylanwednieski@gmail.com"